Invoice/Srini/Laserbeam.Compass/Laserbeam.Compass/Laserbeam.UI.HR/Models/AddMarketPayRange.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Laserbeam.UI.HR.Models
{
    public class AddMarketPayRange
    {
        public string SelectedMarketPayRange { get; set; }
        public int MarketPayRangeNum { get; set; }
        public Nullable<int> JobNum { get; set; }
        public string JobCode { get; set; }
        public Nullable<int> GradeNum { get; set; }
        public string Grade { get; set; }
        public Nullable<int> EmployeeNum { get; set; }
        public string EmployeeName { get; set; }
        public string EmployeeID { get; set; }
        [DisplayFormat(DataFormatString = "{0:n0}", ApplyFormatInEditMode = true)]
        public Nullable<decimal> CurrentMin { get; set; }
        [DisplayFormat(DataFormatString = "{0:n0}", ApplyFormatInEditMode = true)]
        public Nullable<decimal> CurrentMid { get; set; }
        [DisplayFormat(DataFormatString = "{0:n0}", ApplyFormatInEditMode = true)]
        public Nullable<decimal> CurrentMax { get; set; }
        [DisplayFormat(DataFormatString = "{0:n0}", ApplyFormatInEditMode = true)]
        public Nullable<decimal> FutureMin { get; set; }
        [DisplayFormat(DataFormatString = "{0:n0}", ApplyFormatInEditMode = true)]
        public Nullable<decimal> FutureMid { get; set; }
        [DisplayFormat(DataFormatString = "{0:n0}", ApplyFormatInEditMode = true)]
        public Nullable<decimal> FutureMax { get; set; }
        [DisplayFormat(DataFormatString = "{0:n0}", ApplyFormatInEditMode = true)]
        public Nullable<decimal> HourlyCurrentMin { get; set; }
        [DisplayFormat(DataFormatString = "{0:n0}", ApplyFormatInEditMode = true)]
        public Nullable<decimal> HourlyCurrentMid { get; set; }
        [DisplayFormat(DataFormatString = "{0:n0}", ApplyFormatInEditMode = true)]
        public Nullable<decimal> HourlyCurrentMax { get; set; }
        [DisplayFormat(DataFormatString = "{0:n0}", ApplyFormatInEditMode = true)]
        public Nullable<decimal> HourlyFutureMin { get; set; }
        [DisplayFormat(DataFormatString = "{0:n0}", ApplyFormatInEditMode = true)]
        public Nullable<decimal> HourlyFutureMid { get; set; }
        [DisplayFormat(DataFormatString = "{0:n0}", ApplyFormatInEditMode = true)]
        public Nullable<decimal> HourlyFutureMax { get; set; }
        public bool IsEdit { get; set; }
    }
}

Invoice/Srini/Laserbeam.Compass/Laserbeam.Compass/Laserbeam.UI.HR/Controllers/MarketPayRangeController.cs
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using Laserbeam.BusinessObject.Common;
using Laserbeam.Constant.HR;
using Laserbeam.ProcessManager.Interfaces.Common;
using Laserbeam.UI.HR.Common;
using Laserbeam.UI.HR.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Laserbeam.UI.HR.Controllers
{
    [AuthorizeUser(UserRoleConstants.AllRoles)]
    public class MarketPayRangeController : Controller
    {
        #region Fields
        // Author         :   Arunraj C
        // Creation Date  :   11-OCT-2017 
        /// <summary>
        /// Object of IMarketPayRangeProcessManager
        /// </summary>
        private IMarketPayRangeProcessManager m_marketPayRangeProcessManager;
        private SessionManager m_sessionManager;
        #endregion

        #region Constructor
        // Author         :   Arunraj C
        // Creation Date  :   11-OCT-2017 
        /// <summary>
        /// Initialize the processManager and session 
        /// </summary>
        /// <param name="marketPayRangeProcessManager">Object of IMarketPayRangeProcessManager</param>
        /// <param name="sessionManager">Object of SessionManager</param>
        public MarketPayRangeController(IMarketPayRangeProcessManager marketPayRangeProcessManager, SessionManager sessionManager)
        {
            m_marketPayRangeProcessManager = marketPayRangeProcessManager;
            m_sessionManager = sessionManager;
        }
        #endregion


        // GET: MarketPayRange
        [HttpGet]
        public ActionResult Home()
        {
            var busSettingData = m_marketPayRangeProcessManager.GetBusSetting();
            var selectedMarketPayRange = busSettingData.MarketPayRange;
            MarketPayRangeModel model = new MarketPayRangeModel();
            model.SelectedMarketPayRange = selectedMarketPayRange;
            return View(model);
        }

        //[HttpGet]
        //public PartialViewResult _Reportees(string selectedMarketPayRange)
        //{           
        //    MarketPayRangeModel model = new MarketPayRangeModel();
        //    model.SelectedMarketPayRange = selectedMarketPayRange;
        //    return PartialView(model);
        //}
        [HttpPost]
        public async Task<JsonResult> _Reportees(string selectedMarketPayRange, bool isToggleSwitch = false)
        {
            if (isToggleSwitch)
            {
                BusSettingModel busSetting = new BusSettingModel();
                busSetting.MarketPayRange = selectedMarketPayRange;
                await m_marketPayRangeProcessManager.SetBusSetting(busSetting);
            }            
            return Json("Success",JsonRequestBehavior.AllowGet);
        }

        public async Task<JsonResult> _GetMarketPayRangeReportees([DataSourceRequest]DataSourceRequest request, string selectedMarketPayRange)
        {
            var userModel = m_sessionManager.GetSession<UserModel>(SessionConstants.UserModel);
            var loginUserNum = userModel.UserNum;
            var marketPayRangeGridData = await m_marketPayRangeProcessManager.GetMarketPayRangeData(loginUserNum, selectedMarketPayRange);
            return Json(marketPayRangeGridData.ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public PartialViewResult _AddMarketPayRange(string selectedValue = "", int marketPayRangeNum = 0,bool isEdit = false)
        {
            var busSettingData = m_marketPayRangeProcessManager.GetBusSetting();
            AddMarketPayRange model = new AddMarketPayRange();
            ViewBag.SelectedMarketPayRange = busSettingData.MarketPayRange;
            model.MarketPayRangeNum = marketPayRangeNum;
            model.JobCode = selectedValue;
            model.Grade = selectedValue;
            model.EmployeeID = selectedValue;
            model.IsEdit = isEdit;
            if (marketPayRangeNum > 0)
            {
                var getData = m_marketPayRangeProcessManager.GetSelectedMarketPayRange(marketPayRangeNum, busSettingData.MarketPayRange);
                model.MarketPayRangeNum = getData.MarketPayRangeNum;
                model.JobNum = getData.JobNum;
                model.JobCode = getData.JobCode;
                model.GradeNum = getData.GradeNum;
                model.Grade = getData.Grade;
                model.EmployeeNum = getData.EmployeeNum;
                model.EmployeeName = getData.EmployeeName;
                model.EmployeeID = getData.EmployeeID;
                model.CurrentMin = getData.CurrentMin;
                model.CurrentMid = getData.CurrentMid;
                model.CurrentMax = getData.CurrentMax;
                model.HourlyCurrentMin = getData.HourlyCurrentMin;
                model.HourlyCurrentMid = getData.HourlyCurrentMid;
                model.HourlyCurrentMax = getData.HourlyCurrentMax;
                model.FutureMin = getData.FutureMin;
                model.FutureMid = getData.FutureMid;
                model.FutureMax = getData.FutureMax;
                model.HourlyFutureMin = getData.HourlyFutureMin;
                model.HourlyFutureMid = getData.HourlyFutureMid;
                model.HourlyFutureMax = getData.HourlyFutureMax;               
            }
            ViewBag.SelectedValue = selectedValue;
            return PartialView(model);
        }

        [HttpPost]
        public async Task<ActionResult> _AddMarketPayRange(AddMarketPayRange model)
        {
            var busSettingData = m_marketPayRangeProcessManager.GetBusSetting();
            string updateDataValue = "";
            if (model.JobCode != null)
                updateDataValue = model.JobCode;
            else if(model.Grade != null)
                updateDataValue = model.Grade;
            else
                updateDataValue = model.EmployeeID;
            bool IsExisting = false;
            if(!model.IsEdit)
                IsExisting = m_marketPayRangeProcessManager.IsMarketDataExist(busSettingData.MarketPayRange, updateDataValue);
            if(!IsExisting)
            {
                var userModel = m_sessionManager.GetSession<UserModel>(SessionConstants.UserModel);
                var loginUserNum = userModel.UserNum;
                var mUpadteModel = new MarketPayRangeModel
                {
                    MarketPayRangeNum = model.MarketPayRangeNum,
                    JobNum = model.JobNum,
                    JobCode = model.JobCode,
                    GradeNum = model.GradeNum,
                    Grade = model.Grade,
                    EmployeeNum = model.EmployeeNum,
                    EmployeeName = model.EmployeeName,
                    EmployeeID = model.EmployeeID,
                    CurrentMin = model.CurrentMin,
                    CurrentMid = model.CurrentMid,
                    CurrentMax = model.CurrentMax,
                    HourlyCurrentMin = model.HourlyCurrentMin,
                    HourlyCurrentMid = model.HourlyCurrentMid,
                    HourlyCurrentMax = model.HourlyCurrentMax,
                    FutureMin = model.FutureMin,
                    FutureMid = model.FutureMid,
                    FutureMax = model.FutureMax,
                    HourlyFutureMin = model.HourlyFutureMin,
                    HourlyFutureMid = model.HourlyFutureMid,
                    HourlyFutureMax = model.HourlyFutureMax
                };
                
               await  m_marketPayRangeProcessManager.AddUpdateMarketPayRange(mUpadteModel, loginUserNum);
            }
            else
            {
                return Json("already exists", JsonRequestBehavior.AllowGet);
            }
            return Json("Success",JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public PartialViewResult _FilterSort(string selectedMarketPayRange)
        {
            List<SelectListItem> list = new List<SelectListItem>();            
            if (selectedMarketPayRange.ToLower() == "jobcode")
                list.Add(new SelectListItem { Text = "Job Code", Value = "JobCode" });                
            else if (selectedMarketPayRange.ToLower() =="grade")
                list.Add(new SelectListItem { Text = "Grade", Value = "GradeCode" });
            else if (selectedMarketPayRange.ToLower() == "byemployee")
            {
                list.Add(new SelectListItem { Text = "EmployeeID", Value = "EmployeeID" });
                list.Add(new SelectListItem { Text = "Employee Name", Value = "EmployeeName" });
            }
            list.Add(new SelectListItem { Text = "Current Min", Value = "CurrentMin" });
            list.Add(new SelectListItem { Text = "Current Mid", Value = "CurrentMid" });
            list.Add(new SelectListItem { Text = "Current Max", Value = "CurrentMax" });
            list.Add(new SelectListItem { Text = "Hourly Current Min", Value = "HourlyCurrentMin" });
            list.Add(new SelectListItem { Text = "Hourly Current Mid", Value = "HourlyCurrentMid" });
            list.Add(new SelectListItem { Text = "Hourly Current Max", Value = "HourlyCurrentMax" });
            list.Add(new SelectListItem { Text = "New Min", Value = "FutureMin" });
            list.Add(new SelectListItem { Text = "New Mid", Value = "FutureMid" });
            list.Add(new SelectListItem { Text = "New Max", Value = "FutureMax" });
            list.Add(new SelectListItem { Text = "Hourly New Min", Value = "HourlyFutureMin" });
            list.Add(new SelectListItem { Text = "Hourly New Mid", Value = "HourlyFutureMid" });
            list.Add(new SelectListItem { Text = "Hourly New Max", Value = "HourlyFutureMax" });
            return PartialView(list);
        }
    }
}

Invoice/Srini/Laserbeam.Compass/Laserbeam.Compass/Laserbeam.UI.HR/Views/MarketPayRange/_AddMarketPayRange.cshtml
@model Laserbeam.UI.HR.Models.AddMarketPayRange
@using Laserbeam.Constant.HR
@{
    //string readonlyText = Model.MarketPayRangeNum != 0 ? "@readonly" : "";
    string headerText = Model.MarketPayRangeNum != 0 ? "Edit Market Pay Range" : "Add Market Pay Range";
    string marketPayRangeValue = ViewBag.SelectedMarketPayRange;
}
<!-- Add market pay range modal -->
<div class="modal fade" id="AddMarketpayrange" tabindex="-1" role="dialog" aria-labelledby="AddMarketpayrange">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="myModalLabel">@headerText</h4>
            </div>
            @using (Ajax.BeginForm("_AddMarketPayRange", "MarketPayRange", new AjaxOptions { HttpMethod = "POST", OnBegin = "OnBeginMarketPayRange", OnSuccess = "onSuccessUpdateMarketPayRange" }, new { id = "formIdAddMarketPayRange" }))
            {
                <div class="modal-body">
                    <div class="row">
                        <div class="col-md-3 gradetit">
                            @if (ViewBag.SelectedMarketPayRange == MarketPayRangeConstants.JobCode)
                            {
                                <span>Job Code</span>
                            }
                            else if (ViewBag.SelectedMarketPayRange == MarketPayRangeConstants.Grade)
                            {
                                <span>Grade</span>
                            }
                            else
                            {
                                <span>Employee</span>
                            }
                            @Html.Hidden("SelectedMarketPayRange", marketPayRangeValue)
                            @Html.HiddenFor(m => m.MarketPayRangeNum)
                            @Html.HiddenFor(m => m.IsEdit)
                        </div>
                        <div class="col-md-9">
                            @if (ViewBag.SelectedMarketPayRange == MarketPayRangeConstants.JobCode)
                            {
                                @Html.TextBoxFor(m => m.JobCode, ViewBag.SelectedValue != "" ? (object)new { id = "idMarPayRangeJob", @class = "form-control form-border", required = "required", @readonly = "readonly" } : new { id = "idMarPayRangeJob", @class = "form-control form-border", required = "required" })
                            }
                            else if (ViewBag.SelectedMarketPayRange == MarketPayRangeConstants.Grade)
                            {
                                @Html.TextBoxFor(m => m.Grade, ViewBag.SelectedValue != "" ? (object)new { id = "idMarPayRangeGrade", @class = "form-control form-border", required = "required", @readonly = "readonly" } : new { id = "idMarPayRangeGrade", @class = "form-control form-border", required = "required" })
                            }
                            else
                            {
                                @Html.TextBoxFor(m => m.EmployeeID, new { id = "idMarPayRangeEmployee", @class = "form-control form-border", @readonly = "readonly" })
                            }
                            <div id="valdationErrorMsg" style="color:red;display:none;position: absolute;"></div>
                        </div>
                    </div>
                    <div class="row top-pad">
                        <div class="col-md-12 titletxt">Current Range :</div>
                    </div>
                    <div class="row">
                        <div class="col-md-3"></div>
                        <div class="col-md-3 blutxt">Min</div>
                        <div class="col-md-3 blutxt">Mid</div>
                        <div class="col-md-3 blutxt">Max</div>
                    </div>
                    <div class="row smallpadtop">
                        <div class="col-md-3">Hourly</div>
                        <div class="col-md-3">@Html.TextBoxFor(m => m.HourlyCurrentMin, String.Format("{0:n5}", Model.HourlyCurrentMin), new { @class = "form-control market-numbers-hourly" })</div>
                        <div class="col-md-3">@Html.TextBoxFor(m => m.HourlyCurrentMid, String.Format("{0:n5}", Model.HourlyCurrentMid), new { @class = "form-control market-numbers-hourly" })</div>
                        <div class="col-md-3">@Html.TextBoxFor(m => m.HourlyCurrentMax, String.Format("{0:n5}", Model.HourlyCurrentMax), new { @class = "form-control market-numbers-hourly" })</div>
                    </div>
                    <div class="row top-pad">
                        <div class="col-md-3">Annual</div>
                        <div class="col-md-3">@Html.TextBoxFor(m => m.CurrentMin, String.Format("{0:n2}", Model.CurrentMin), new { @class = "form-control market-numbers-annual" })</div>
                        <div class="col-md-3">@Html.TextBoxFor(m => m.CurrentMid, String.Format("{0:n2}", Model.CurrentMid), new { @class = "form-control market-numbers-annual" })</div>
                        <div class="col-md-3">@Html.TextBoxFor(m => m.CurrentMax, String.Format("{0:n2}", Model.CurrentMax), new { @class = "form-control market-numbers-annual" })</div>
                    </div>
                    <div class="row top-pad">
                        <div class="col-md-12 titletxt">New Range :</div>
                    </div>
                    <div class="row">
                        <div class="col-md-3"></div>
                        <div class="col-md-3 blutxt">Min</div>
                        <div class="col-md-3 blutxt">Mid</div>
                        <div class="col-md-3 blutxt">Max</div>
                    </div>
                    <div class="row smallpadtop">
                        <div class="col-md-3">Hourly</div>
                        <div class="col-md-3">@Html.TextBoxFor(m => m.HourlyFutureMin, String.Format("{0:n5}", Model.HourlyFutureMin), new { @class = "form-control market-numbers-hourly" })</div>
                        <div class="col-md-3">@Html.TextBoxFor(m => m.HourlyFutureMid, String.Format("{0:n5}", Model.HourlyFutureMid), new { @class = "form-control market-numbers-hourly" })</div>
                        <div class="col-md-3">@Html.TextBoxFor(m => m.HourlyFutureMax, String.Format("{0:n5}", Model.HourlyFutureMax), new { @class = "form-control market-numbers-hourly" })</div>
                    </div>
                    <div class="row top-pad">
                        <div class="col-md-3">Annual</div>
                        <div class="col-md-3">@Html.TextBoxFor(m => m.FutureMin, String.Format("{0:n2}", Model.FutureMin), new { @class = "form-control market-numbers-annual" })</div>
                        <div class="col-md-3">@Html.TextBoxFor(m => m.FutureMid, String.Format("{0:n2}", Model.FutureMid), new { @class = "form-control market-numbers-annual" })</div>
                        <div class="col-md-3">@Html.TextBoxFor(m => m.FutureMax, String.Format("{0:n2}", Model.FutureMax), new { @class = "form-control market-numbers-annual" })</div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-cancel" data-dismiss="modal"><i class="fa fa-ban"></i> Cancel</button>
                    <button type="submit" class="btn btn-info prim-btn">Save</button>
                </div>
            }
        </div>
    </div>
</div>

Invoice/Srini/Laserbeam.Compass/Laserbeam.Compass/Laserbeam.UI.HR/Views/MarketPayRange/_Reportees.cshtml
@model Laserbeam.BusinessObject.Common.MarketPayRangeModel
@using Laserbeam.BusinessObject.Common
@using Laserbeam.Constant.HR
@{ 
    Layout = null;
    bool IsJobCodeEnable = (Model.SelectedMarketPayRange == MarketPayRangeConstants.JobCode) ? true : false;
    bool IsGradeEnable = (Model.SelectedMarketPayRange == MarketPayRangeConstants.Grade) ? true : false;
    bool IsEmployeeEnable = (Model.SelectedMarketPayRange == MarketPayRangeConstants.ByEmployee) ? true : false;
}
<script>
    selectedMarketPayRange = '@Model.SelectedMarketPayRange';
</script>

@(Html.Kendo().Grid<MarketPayRangeGridModel>
        ().Name("MarketPayRangeReporteeGrid")
        .Columns(columns =>
        {
            columns.Bound(m => m.JobCode).Title("Job Code").ClientTemplate("<a id='lnkMarketPayRangeJobCode' data-value='#=JobCode#' data-marketpayrange-num='#=MarketPayRangeNum#'>#=JobCode#</a>").Width(200).HeaderHtmlAttributes(new { style = "text-align:left !important;border-right: 1px solid #dbdbdb;vertical-align: middle;" }).HtmlAttributes(new { @class="grid-content-border-right"});  //.HeaderHtmlAttributes(new { @class = "columnSize-180 width150 text-center" }).HtmlAttributes(new { @class = "columnSize-180 width150 text-center" });
            columns.Bound(m => m.GradeCode).Title("Grade").ClientTemplate("<a id='lnkMarketPayRangeGradeCode' data-value='#=GradeCode#' data-marketpayrange-num='#=MarketPayRangeNum#'>#=GradeCode#</a>").Width(200).HeaderHtmlAttributes(new { style = "text-align:left !important;border-right: 1px solid #dbdbdb;vertical-align: middle;" }).HtmlAttributes(new { @class = "grid-content-border-right" });
            columns.Bound(m => m.EmployeeID).Title("Employee ID").HeaderTemplate("Employee Name <br> Employee ID").ClientTemplate("<a id='lnkMarketPayRangeEmployeeID' data-value='#=EmployeeID#' data-marketpayrange-num='#=MarketPayRangeNum#'>#=EmployeeName#</a><br>#=EmployeeID#").Width(250).HeaderHtmlAttributes(new { style= "text-align:left !important;border-right: 1px solid #dbdbdb;vertical-align: middle;" }).HtmlAttributes(new { @class = "grid-content-border-right" });
            columns.Bound(m => m.EmployeeName).Visible(false);//.Title("Employee Name").Width(200).HeaderHtmlAttributes(new { style = "text-align:left !important;border-right: 1px solid #dbdbdb;vertical-align: middle;" }).HtmlAttributes(new { @class = "grid-content-border-right" });
            columns.Group(group => group.Title("Current Min").HeaderHtmlAttributes(new { style = "text-align:center !important;" })
            .Columns(info =>
            {
                info.Bound(m => m.CurrentMin).Title("Annual").Format("{0:n2}").HeaderHtmlAttributes(new { style = "text-align:center !important;" }).HtmlAttributes(new { style = "text-align:center !important;" });
                info.Bound(m => m.HourlyCurrentMin).Title("Hourly").Format("{0:n5}").HeaderHtmlAttributes(new { style = "text-align:center !important;" }).HtmlAttributes(new { style = "text-align:center !important;" });
            })
            );
            columns.Group(group => group.Title("Current Mid").HeaderHtmlAttributes(new { style = "text-align:center !important;" })
            .Columns(info =>
            {
                info.Bound(m => m.CurrentMid).Title("Annual").Format("{0:n2}").HeaderHtmlAttributes(new { style = "text-align:center !important;" }).HtmlAttributes(new { style = "text-align:center !important;" });
                info.Bound(m => m.HourlyCurrentMid).Title("Hourly").Format("{0:n5}").HeaderHtmlAttributes(new { style = "text-align:center !important;" }).HtmlAttributes(new { style = "text-align:center !important;" });
            })
            );
            columns.Group(group => group.Title("Current Max").HeaderHtmlAttributes(new { style = "text-align:center !important;" })
            .Columns(info =>
            {
                info.Bound(m => m.CurrentMax).Title("Annual").Format("{0:n2}").HeaderHtmlAttributes(new { style = "text-align:center !important;" }).HtmlAttributes(new { style = "text-align:center !important;" });
                info.Bound(m => m.HourlyCurrentMax).Title("Hourly").Format("{0:n5}").HeaderHtmlAttributes(new { style = "text-align:center !important;" }).HtmlAttributes(new { style = "text-align:center !important;" });
            })
            );
            columns.Group(group => group.Title("New Min").HeaderHtmlAttributes(new { style = "text-align:center !important;" })
            .Columns(info =>
            {
                info.Bound(m => m.FutureMin).Title("Annual").Format("{0:n2}").HeaderHtmlAttributes(new { style = "text-align:center !important;" }).HtmlAttributes(new { style = "text-align:center !important;" });
                info.Bound(m => m.HourlyFutureMin).Title("Hourly").Format("{0:n5}").HeaderHtmlAttributes(new { style = "text-align:center !important;" }).HtmlAttributes(new { style = "text-align:center !important;" });
            })
            );
            columns.Group(group => group.Title("New Mid").HeaderHtmlAttributes(new { style = "text-align:center !important;" })
           .Columns(info =>
           {
               info.Bound(m => m.FutureMid).Title("Annual").Format("{0:n2}").HeaderHtmlAttributes(new { style = "text-align:center !important;" }).HtmlAttributes(new { style = "text-align:center !important;" });
               info.Bound(m => m.HourlyFutureMid).Title("Hourly").Format("{0:n5}").HeaderHtmlAttributes(new { style = "text-align:center !important;" }).HtmlAttributes(new { style = "text-align:center !important;" });
           })
           );
            columns.Group(group => group.Title("New Max").HeaderHtmlAttributes(new { style = "text-align:center !important;" })
           .Columns(info =>
           {
               info.Bound(m => m.FutureMax).Title("Annual").Format("{0:n2}").HeaderHtmlAttributes(new { style = "text-align:center !important;" }).HtmlAttributes(new { style = "text-align:center !important;" });
               info.Bound(m => m.HourlyFutureMax).Title("Hourly").Format("{0:n5}").HeaderHtmlAttributes(new { style = "text-align:center !important;" }).HtmlAttributes(new { style = "text-align:center !important;" });
           })
           );

        })
        .DataSource(dataSource => dataSource.Ajax().Read(read => read.Action("_GetMarketPayRangeReportees", "MarketPayRange").Data("GetReporteesMarketPayRangeParam"))//.PageSize(25).ServerOperation(true).Batch(true)
        )
        .Sortable().Resizable(resize => resize.Columns(false))
        //.Pageable()
        .Scrollable(scrollable => scrollable.Height(300))
        .Selectable(selectable => selectable
            //.Mode(GridSelectionMode.Multiple)
            .Type(GridSelectionType.Row))
        .Events(x => x.DataBound("onMarketPayRangeDataBound").Change("Grid_OnRowSelect"))
)